name = "memos-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"
routes = [
  { pattern = "memos-api.mgt.xx.kg", custom_domain = true }
]
compatibility_flags = ["nodejs_compat"]

[vars]
LOG_LEVEL = "info"
BASE_URL = "https://mmos.pages.dev" # 👈 这里必须保留 https://，且末尾不要加 /
JWT_SECRET = "abcdefghijklmnopqrstuvwxyz1234567890ABCDEF" # 👈 确保长密钥在这里


# Secrets - set via wrangler secret put
# JWT_SECRET
# ALLOWED_ORIGINS  
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY

# 单 Worker 同源部署：Worker 同时托管前端静态资源与 API

[[d1_databases]]
binding = "DB"
database_name = "memos-db"
database_id = "8d43a949-4075-4e91-84f8-335cae26080c"

[env.staging]
name = "memos-cloudflare-staging"

[env.production]
name = "memos-cloudflare-production" 
